apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-service.default.svc.cluster.local:3000/schakra/terminalService.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: emp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true