apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-deployment
  labels:
    app: emp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: emp
  template:
    metadata:
      labels:
        app: emp
    spec:
      containers:
      - name: emp
        image: docker.io/saschak07/emp